### ISSUE TITLE
local variable 'duration' referenced before assignment

### ISSUE THREAD

**Issue by LeBenLeBen** [sephii/taxi#109]
With a tks file like this:
```
03/07/2017
xxx       0845-0930 xxx
xxx           -1130 xxx
xxx           -? xxx
```
I get this error when I `status` or `edit` with Taxi 4.3.0b1.

```
Traceback (most recent call last):
  File "/usr/local/bin/taxi", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/taxi/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/taxi/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/taxi/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/taxi/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/taxi/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/taxi/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/taxi/lib/python2.7/site-packages/taxi/commands/edit.py", line 33, in edit
    ctx, file_to_edit
  File "/usr/local/lib/taxi/lib/python2.7/site-packages/taxi/commands/base.py", line 45, in get_timesheet_collection_for_context
    return TimesheetCollection.load(entries_file, ctx.obj['settings']['nb_previous_files'], parser)
  File "/usr/local/lib/taxi/lib/python2.7/site-packages/taxi/timesheet/timesheet.py", line 239, in load
    file_path, parser=parser, initial=lambda: timesheet_collection.get_new_timesheets_contents()
  File "/usr/local/lib/taxi/lib/python2.7/site-packages/taxi/timesheet/timesheet.py", line 71, in load
    entries = EntriesCollection(parser, contents)
  File "/usr/local/lib/taxi/lib/python2.7/site-packages/taxi/timesheet/entry.py", line 252, in __init__
    self.init_from_str(entries)
  File "/usr/local/lib/taxi/lib/python2.7/site-packages/taxi/timesheet/entry.py", line 391, in init_from_str
    self.lines = self.parser.parse_text(entries)
  File "/usr/local/lib/taxi/lib/python2.7/site-packages/taxi/timesheet/parser.py", line 316, in parse_text
    parsed_line = self.parse_line(line)
  File "/usr/local/lib/taxi/lib/python2.7/site-packages/taxi/timesheet/parser.py", line 350, in parse_line
    parsed_line = self.create_entry_line_from_text(text)
  File "/usr/local/lib/taxi/lib/python2.7/site-packages/taxi/timesheet/parser.py", line 254, in create_entry_line_from_text
    entry_line = Entry(alias, duration, description, flags=flags, text=line)
UnboundLocalError: local variable 'duration' referenced before assignment
```

**Comment by sephii** [comment]
Thanks for the bug report. Fixed by https://github.com/sephii/taxi/commit/2ffcd89b7911104a3f9c136a4b9e91e755d5791f and released in 4.3.0b2.
