### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by kayoumido** [sephii/taxi#114]
When I tried to install the latest version of taxi (4.4.1)
I got the following error

```
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/taxi/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/usr/local/lib/taxi/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 335, in run
    use_user_site=options.use_user_site,
  File "/usr/local/lib/taxi/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/usr/local/lib/taxi/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 748, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/usr/local/lib/taxi/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 961, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/usr/local/lib/taxi/lib/python3.6/site-packages/pip/_internal/wheel.py", line 466, in move_wheel_files
    msg = message_about_scripts_not_on_PATH(generated_console_scripts)
  File "/usr/local/lib/taxi/lib/python3.6/site-packages/pip/_internal/wheel.py", line 167, in message_about_scripts_not_on_PATH
    os.path.normcase(i) for i in os.environ["PATH"].split(os.pathsep)
  File "/usr/local/lib/taxi/bin/../lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'PATH'
```

As a quick-fix I executed this :
```bash
$ /usr/local/lib/taxi/bin/pip install taxi-zebra
```

**Comment by sephii** [comment]
The docs have been updated to suggest using pipsi.
